import subprocess
import sys
import os
import http.server
import socketserver
import webbrowser
import time


def run_pipeline():
    # List of scripts in execution order
    pipeline_steps = [
        "pipeline.py",
        "analytics.py",
        "predictions.py",
        "3_dimensional_globe.py"
    ]

    print("--- STARTING GLOBAL MARKET PIPELINE ---")

    for script in pipeline_steps:
        if not os.path.exists(script):
            print(f"Error: {script} not found in directory.")
            return False

        print(f"Executing: {script}...")
        result = subprocess.run([sys.executable, script], capture_output=True, text=True)

        if result.returncode == 0:
            print(f"ok {script} completed successfully.")
        else:
            print(f"! Error in {script}:")
            print(result.stderr)
            break

    print("--- PIPELINE FINISHED ---")
    return True


def start_server(port=8000):
    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    file = "global_market_globe.html"
    max_wait = 30  # seconds
    elapsed = 0
    while not os.path.exists(file) and elapsed < max_wait:
        time.sleep(1)
        elapsed += 1

    if not os.path.exists(file):
        print(f"ERROR: {file} was not generated by the pipeline.")
        return

    url = f"http://127.0.0.1:{port}/{file}"
    try:
        handler = http.server.SimpleHTTPRequestHandler
        # suppress the per-request log noise in the terminal
        handler.log_message = lambda *args: None
        httpd = socketserver.ThreadingTCPServer(("127.0.0.1", port), handler)

        print(f"--- STARTING LOCALHOST SERVER ---")
        print(f"Server live at {url}")
        webbrowser.open(url)
        httpd.serve_forever()

    except Exception as e:
        # Open file directly if the server fails
        print(f"Server couldn't start (Error: {e}).")
        print("FALLBACK: Opening the local file directly in your browser...")
        full_path = os.path.abspath(file)
        webbrowser.open(f"file://{full_path}")


if __name__ == "__main__":
    success = run_pipeline()
    if success:
        start_server(port=8000)
    else:
        print("Pipeline failed. Aborting...")