import subprocess
import sys
import os
import http.server
import socketserver
import webbrowser
import time


def run_pipeline():
    # List of scripts in execution order
    pipeline_steps = [
        "pipeline.py",
        "analytics.py",
        "predictions.py",
        "3_dimensional_globe.py"
    ]

    print("--- STARTING GLOBAL MARKET PIPELINE ---")

    for script in pipeline_steps:
        if not os.path.exists(script):
            print(f"Error: {script} not found in directory.")
            continue

        print(f"Executing: {script}...")
        result = subprocess.run([sys.executable, script], capture_output=True, text=True)

        if result.returncode == 0:
            print(f"ok {script} completed successfully.")
        else:
            print(f"! Error in {script}:")
            print(result.stderr)
            break

    print("--- PIPELINE FINISHED ---")


def start_server(port=8000):
    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    file = "global_market_globe.html"
    max_wait = 30  # seconds
    elapsed = 0
    while not os.path.exists(file) and elapsed < max_wait:
        time.sleep(1)
        elapsed += 1

    if not os.path.exists(file):
        print(f"ERROR: {file} was not generated by the pipeline.")
        return

    handler = http.server.SimpleHTTPRequestHandler
    httpd = socketserver.TCPServer(("", port), handler)

    print(f"--- STARTING LOCALHOST SERVER ---")
    print(f"Server running at http://localhost:{port}/" + file)
    print(f"Press Ctrl+C to stop the server and exit.\n")

    webbrowser.open(f"http://localhost:{port}/" + file)

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n--- Shutting down server ---")
        httpd.shutdown()
        sys.exit(0)


if __name__ == "__main__":
    run_pipeline()
    start_server(port=8000)